//#pragma comment(lib, "glfw3.lib")
//#pragma comment(lib, "glew32s.lib")
//#pragma comment(lib, "opengl32.lib")
//#pragma comment(lib, "user32.lib")
//#pragma comment(lib, "gdi32.lib")
//#pragma comment(lib, "shell32.lib")